### ISSUE TITLE
Rethink how we built these filters

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/Rest-Easy#10]
For what it's worth, I think I know WordPress better than most, and I spent 3 hours on this and couldn't figure it out. Are these filters needlessly complicated? 

Why all the converting to and from serialization? Can't we just keep everything in regular PHP arrays, and the do one final serialization at the end?

I was simply trying to include some extra page data on any home page request:

```
    function add_home_grid($post){

        if( $post['meta']['custom_developer_id'] == 'front-page' ) {

            // Get compaines post ID
            $args = array(
                'meta_key'      => 'custom_developer_id',
                'meta_value'    => 'companies',
                'post_type'     => 'page'
            );
            $companies_post = get_posts($args);

            $args = array(
                'posts_per_page'       => -1,
                'orderby'              => 'menu_order',
                'order'                => 'ASC',
                'post_type'            => 'page',
                'post_parent'          => $companies_post->ID,
            );
            $companies_children = get_posts($args);

            $data['companies'] = array();
            foreach ($companies_children as $child) {
                // This crashes the server for some unknown reason
                //$data['companies'][] = apply_filters('rez_serialize_object', $child);
            }
        }

        return $data;
    }
    add_filter('rez_serialize_post', 'add_home_grid');
```

**Comment by drewbaker** [comment]
Thinking more on this, I'm not sure why this all can't just be one filter point, which returns the entire array of data, right before it's serialized.

Like: `add_filter('rez_before_final_serialize', 'callback');` and that has one parameter, which is one giant array of everything that currently gets sent to Vuex. I could then look through this array, add anything I want to it. Maybe this is `rez_build_all_data` but I'm not sure.

I could see having other filters that ran anytime a post is pulled or anytime an attachment is pulled, and I think you have built this, but the way it's done is really confusing. I think it comes down to when you are doing the serializing, but I'm really not sure.

**Comment by jrobson153** [comment]
I think this is mostly a documentation problem.

as you mentioned `rez_build_all_data` is exactly the filter you're looking for, the final step you can add things before it all gets sent to Vuex. I think your confusion here is mostly in the idea of serializers. My definition of a serializer in this context is something like this: "Any time a single object in Wordpress needs to be converted into a `json_encode()`-able array."

So with that in mind a filter like `rez_serialize_post` should only really be used when you want to add or alter single data items on every post. Your unknown reason for the server crashing is an infinite loop, because you're serializing within the serializer. For your use case you are really trying to add data to your query rather than a single post item, so `rez_build_loop_data` or `rez_build_site_data` would be more suitable.

Let's set up a call next week where we can go over the rest easy filters in more detail, and then we can make some decisions on refactoring the filters, the documentation, or both.

**Comment by drewbaker** [comment]
Spoke with John about this, I think the things we need to change to make this easier to understand for a newbie. It's all documentation.

- [ ] Include a Draw.io chart showing the process that goes into building the JSON data
- [ ] Update the documentation to explain the difference between builders and serializes
- [ ] Explain how to avoid infinite loops with serializes
- [ ] Document `get_page_by_dev_id()`

**Comment by SaFrMo** [comment]
Looks good! Assigning to myself.

**Comment by SaFrMo** [comment]
Got back around to this and set up some more complete documentation. I'm removing "Document `get_page_by_dev_id`" because that's a Vuepress concept, not Rest-Easy.
