### ISSUE TITLE
Give filters some context of what they are being built on

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/Rest-Easy#9]
The `rez_gather_related` doesn't give you a post ID of what it the "related" is being built on.

For example, when on the home page, I have a slideshow and a grid of work. So I want to return the children of `home`, and the children of `recent work`. 

It seems to me that the related filter is the closest filter to this, but it doesn't give me any context as to what the "related" is too. It should include a post object as on of the parameters. Like so:

```
function add_home_grid($related, $post){
}
add_filter('rez_gather_related', 'add_home_grid');
```

This way I could test if the home page is being queried, and then to include recent work in the results.

It seems like most of the filters would benefit from adding this parameter where possible (and makes sense).

**Comment by drewbaker** [comment]
We really should update the readme to show the parameters that each filter gets passed too.

**Comment by jrobson153** [comment]
Yea agreed, for the time being I would try to avoid the `rez_gather_related` filter because it's sufficiently more complex than the others and requires you to manually serialize your data which is not ideal.

I think the ideal functionality here is to have the signature be `($related, $post)` like you're suggesting, where `$related` is just a flat array of regular wordpress objects that get serialized AFTER this filter is run. That way you can just dump whatever posts, pages, attachments, etc you need in here and know they will get serialized later on.

This is a pretty simple change, assigning to myself.

**Comment by jrobson153** [comment]
This is now fixed in https://github.com/funkhaus/Rest-Easy/commit/6420e3d50c30f58774c19afa9b2b55feeb383b1d

Very important to keep in mind however that filter functions expecting more than 1 argument must declare it in their `add_filter()` call.

Here's what it looks like:
```
function add_home_grid($related, $post){
  // do something...
}
add_filter('rez_gather_related', 'add_home_grid', 10, 2);
```
